// Autogenerated from Pigeon (v18.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct CoordinatesMessage {
  var lat: Double
  var lng: Double

  static func fromList(_ list: [Any?]) -> CoordinatesMessage? {
    let lat = list[0] as! Double
    let lng = list[1] as! Double

    return CoordinatesMessage(
      lat: lat,
      lng: lng
    )
  }
  func toList() -> [Any?] {
    return [
      lat,
      lng,
    ]
  }
}

private class PlatformGeoLocationCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return CoordinatesMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PlatformGeoLocationCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CoordinatesMessage {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PlatformGeoLocationCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PlatformGeoLocationCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PlatformGeoLocationCodecWriter(data: data)
  }
}

class PlatformGeoLocationCodec: FlutterStandardMessageCodec {
  static let shared = PlatformGeoLocationCodec(readerWriter: PlatformGeoLocationCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PlatformGeoLocation {
  func getHostLanguage() throws -> String
  func getCoordinates(completion: @escaping (Result<CoordinatesMessage, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PlatformGeoLocationSetup {
  /// The codec used by PlatformGeoLocation.
  static var codec: FlutterStandardMessageCodec { PlatformGeoLocationCodec.shared }
  /// Sets up an instance of `PlatformGeoLocation` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PlatformGeoLocation?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getHostLanguageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pigeon_recommendo_geo_location.PlatformGeoLocation.getHostLanguage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getHostLanguageChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getHostLanguage()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getHostLanguageChannel.setMessageHandler(nil)
    }
    let getCoordinatesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pigeon_recommendo_geo_location.PlatformGeoLocation.getCoordinates\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCoordinatesChannel.setMessageHandler { _, reply in
        api.getCoordinates { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCoordinatesChannel.setMessageHandler(nil)
    }
  }
}
