name: recommendo
description: OTUS Course project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.3.3

dependencies:
  animations: ^2.0.11
  device_preview: ^1.1.0
  dio: ^5.4.2+1
  equatable: ^2.0.5
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  firebase_ui_auth:
    path: packages/firebase_ui_auth
    version: ^1.13.1
  firebase_ui_oauth_apple: ^1.2.19
  firebase_ui_oauth_google: ^1.3.1
  flare_flutter: ^3.0.2
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_wizard: ^2.0.5
  get_it: ^7.6.8
  go_router: ^13.2.3
  google_maps_places_autocomplete_widgets:
    path: packages/google_maps_places_autocomplete_widgets
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  retrofit: ^4.1.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  retrofit_generator: '>=7.0.0 <8.0.0'
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/flares/
  fonts:
    - family: Raleway
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
      

dependency_overrides:
  firebase_ui_auth:
    path: packages/firebase_ui_auth